### ISSUE TITLE
[VLRP] Bug Report - Phones not working

### ISSUE THREAD

**Issue by FriarTuck369** [VacationLifeRP/VLRP-BugReports#2]
**Describe the bug**

Trying to open the phone fails

**To Reproduce**

Simply try and open your phone

**Expected behavior**
I get a notification saying " #FF1D25 "

**Screenshots**

![image](https://user-images.githubusercontent.com/116926325/198826348-29729380-3f3b-4a47-8606-ab9f3414ae25.png)

**In-Game Feature (please complete the following information):**

The Phone lets us communicate and tweet out hood rat shit :)

**Additional context**

I live this form of bug reporting much more :)

**Discord Username**
Friar Tuck

**Comment by YvanCywan** [comment]
Additional Information for ease of access:
![Screenshot_from_2022-10-28_23-47-23](https://user-images.githubusercontent.com/13180679/198835429-6061b9a0-9f8a-4ae0-9203-9b0c401414c9.png)
Seems to be a global variable error, will do some more testing with it

**Comment by YvanCywan** [comment]
I've uploaded a pull request with the fix, this issue will be closed on merge.
