### ISSUE TITLE
[VLRP] Bug Report : AmmoNation@646 - Player Owned : Restocking Mission : No Location given to pickup restock

### ISSUE THREAD

**Issue by FriarTuck369** [VacationLifeRP/VLRP-BugReports#3]
**Describe the bug**

For restocking the store, I put in my request for restock and that works. But after accepting the mission and going outside to get the location, nothing appears on the map. 

>>> Side Note, Ares has a market and when he is restocking, he does the same steps and gets the same results and I do...

**To Reproduce**
Go to Customer side of counter > Flex E > the TAB on the Right side of the screen, Missions = Click > choose restocking mission (also the pay out for this service seems excessive imo) > I get a notification that my map will be updated > I go outside and open my map... Nothing

**Expected behavior**

I would expect for one of the following to happen:
1) The location is marked on the map and a GPS route was already set
2) A New Item appeared on my map that I could select to set a GPS route to
3) I get a Text or Email from the store telling me " Go to the location below to collect the pick-up " and then message include the needed GPS location

**Screenshots**
F8 Log - I entered my title [AmmoNation] closed F8 accepted the mission and reopened F8 and this was the output:
![image](https://user-images.githubusercontent.com/116926325/198827550-2dc83cb7-ad52-43e4-b55c-c4ce5fa2d29b.png)

I have video as well:
https://youtu.be/aP-Nl0chYVI

**In-Game Feature (please complete the following information):**
This is the restocking of my player (me) owned store
+ once this is fixed, it should also take care of the same issue Ares is having

**Additional context**
As side questions: 
1. Could the music in store be controlled by a custom url? (spotify channel)
2. I have also noticed that none of the clips will attach to any of the weapons.
3. For a store like this, are there any other options for the interface to manage the store stock and inventory? Not speaking to the missions for restocking but just to manage it.
4. A good bit of the items in my AmmoNation store does not seem to have the images loaded with them, can I help by providing images?
5. As a Citizen of this great city, do I automatically get access to a repair bench somewhere so I can repair my weapons? If not as a Citizen, Would I get access to this as a Ammo/ Weapons Store owner? If I DO have access, I cant seem to find mine. Could I get a point int he right direction?

**Discord Username**
Friar Tuck

**Comment by YvanCywan** [comment]
I've found the issue and am working on it, will take a little bit as some of the logic needs a bit of a rework, this Issue will remain open until merge.

Thank you for the report

**Comment by YvanCywan** [comment]
Has been merged, issue closed
