### ISSUE TITLE
[VLRP] Bug Report : Electrician Job - Truck Does Not Spawn to Start

### ISSUE THREAD

**Issue by FriarTuck369** [VacationLifeRP/VLRP-BugReports#4]
**Describe the bug**
Arrived @ the Electrician job > The " PAY " marker is visible  > went to the area to grab the truck and the " E option " appeared > Flexed E = nothin and the marker disappeared and will not re-appear 

**To Reproduce**
GOTO: Electrician Job @ 171
      > Walk over to the 2nd parking spot away from the pay door, to the right
            > E to Start the mission appears, FLEX E

**Expected behavior**
One of the expected electrical automobiles appear and the citizen can start the mission by checking the map and seeing the sites that need to be visited and repaired

**Screenshots**
![image](https://user-images.githubusercontent.com/116926325/198829910-257f25c2-6b74-4c06-95f1-5e3c42f88b6f.png)

**In-Game Feature (please complete the following information):**
Electrician Job to start out making money

**Additional context**
This stopped working around 10/21/22... that is when I noticed it first 

**Discord Username**
Friar Tuck

**Comment by YvanCywan** [comment]
Issue is resolved, and everything is functioning, closed on merge
