### ISSUE TITLE
[VLRP] Bug Report - UI has disappeared

### ISSUE THREAD

**Issue by x1ares1x1** [VacationLifeRP/VLRP-BugReports#7]
**Describe the bug**
The UI has disappeared. When you press F9 to access the UI settings the mouse will appear but nothing else and you are stuck, not able to do anything but log out. When you Press F8 there is a Script Error that shows. I have included a screenshot of that.

**To Reproduce**
1. UI is gone as soon as you log in
2. Press F9
3. Mouse will appear but nothing else

**Expected behavior**
UI should be there as soon as you log in and when you press F9 it should bring up the settings for the UI

**Screenshots**

![NoUI](https://user-images.githubusercontent.com/114434505/200127892-2ba7016d-6c0b-4c38-92a1-7277558e5d0f.png)

![ScriptError](https://user-images.githubusercontent.com/114434505/200127899-1efdce60-f829-4773-8b18-cbd72c26421e.png)

**In-Game Feature (please complete the following information):**
Please describe the in-game feature.

**Additional context**

**Discord Username**
x1ares1x1

**Comment by FriarTuck369** [comment]
The same thing is happening to me. 
FT0369

**Comment by YvanCywan** [comment]
I will continue to look into this, I have not found the issue and the F8 error displayed is likely not to be connected. Bare with, I will ask for a reversal on the change that happened last night to see if that eases the situation.

**Comment by FriarTuck369** [comment]
This issue looks to be resolved
